export const EDIT_USER_ADDRESS = 'EDIT_USER_ADDRESS';
export const EDIT_USER_NETWORK = 'EDIT_USER_NETWORK';
export const EDIT_CONTRACT_INFOS = 'EDIT_CONTRACT_INFOS';
export const EDIT_USER_WATCH_TRANSACTION = 'EDIT_USER_WATCH_TRANSACTION';
export const EDIT_USER_WATCH_CONFIRMATION = 'EDIT_USER_WATCH_CONFIRMATION';
export const EDIT_USER_WATCH_CONTRACT = 'EDIT_USER_WATCH_CONTRACT';
